[config]
blueprint = "false"

[application]
theme_colors = [] # TODO: fix this, this shouldn't be required

[deployment]
application_name = "Hummingbird"
application_generic_name = "Music Player"
application_machine_name = "hummingbird-player"
organization_name = "mailliw"
desktop_entry = "org.mailliw.hummingbird"
desktop_entry_categories = ["Audio", "AudioVideo"]
icon = "res/icon.svg"
disk_image_background = "res/dmg-background.svg"

[deployment."aarch64-apple-darwin"]
icon = "res/macos-icon.svg"

[deployment."x86_64-apple-darwin"]
icon = "dist/macos-icon.svg"
